name: Deploy to Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
    types: [closed]

jobs:
  deploy:
    # This logic ensures the job only runs on a push OR a successful merge
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 66.29.146.99
          username: shinliih
          port: 21098
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd directory.gsfnational.org/MF
            git stash
            git pull origin development
            php artisan migrate --force
            php artisan optimize:clear
            # php artisan db:seed --class=AwardShortlistStageSeeder --force
            echo "Deployment to Server completed!"
