name: Deploy to GSF & GYF Servers

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  deploy-gsf:
    name: Deploy to GSF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GSF server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 162.0.232.109
          username: shinliih
          key: ${{ secrets.DEPLOY_KEY_GSF }}
          port: 21098
          script_stop: true
          script: |
            echo "Deploying to GSF..."
            cd /home/shinliih/directory.gsfnational.org/MF
            git fetch --all
            git reset --hard origin/development
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            echo "Deployment to GSF completed!"

  # deploy-gyf:
  #   name: Deploy to GYF
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Deploy to GYF server
  #       uses: appleboy/ssh-action@v0.1.8
  #       with:
  #         host: 198.54.115.222
  #         username: gyfnbpbo
  #         key: ${{ secrets.DEPLOY_KEY_GYF }}
  #         port: 21098
  #         script_stop: true
  #         script: |
  #           echo "Deploying to GYF..."
  #           cd /home/gyfnbpbo/registration.gyfnational.org/apps
  #           git fetch --all
  #           git reset --hard origin/development
  #           php artisan migrate --force
  #           php artisan cache:clear
  #           php artisan config:clear
  #           php artisan route:clear
  #           php artisan view:clear
  #           echo "Deployment to GYF completed!"
